### ISSUE TITLE
MacOS Continued Issue 😢 

### ISSUE THREAD

**Issue by Austin1** [ScriptPup/sqltools-teradata-driver#24] opened 2023-05-05 20:42 UTC
**Describe the bug**
Well, I thought updating the node-js teradata driver fixed the issue, but after this was deployed and installed in my VScode, I'm getting errors still.

**To Reproduce**
Use M1 Macbook Pro
Open VS Code

**Expected behavior**

**Screenshots**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/341408/236565029-4dd91a87-febf-49f8-af0b-8d1555e02ed5.png">

**Desktop (please complete the following information):**
 - OS: Monterey
 - Browser edge

**Additional context**

```
[1683319136874] INFO  (ext): SQLTools is starting
[1683319136876] INFO  (ext): initializing language client...
[1683319136877] INFO  (ext): Registering client for languages [{"scheme":"sqltools"},{"language":"sql","scheme":"untitled"},{"language":"sql","scheme":"file"},{"language":"sql","scheme":"sqltools"}]
    ns: "lc"
[1683319136879] INFO  (ext): loading plugins...
[1683319136880] INFO  (ext): registering Formatter Plugin.
    plugin: {
      "name": "Formatter Plugin"
    }
[1683319136880] INFO  (ext): registering Connection Manager Plugin.
    plugin: {
      "name": "Connection Manager Plugin"
    }
[1683319136880] INFO  (ext): registering CodeLens Plugin.
    plugin: {
      "name": "CodeLens Plugin",
      "registeredLanguages": []
    }
[1683319136881] INFO  (ext): registering Dependency Manager Plugin.
    plugin: {
      "name": "Dependency Manager Plugin",
      "installingDrivers": []
    }
[1683319136883] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1683319136883] INFO  (ext): registering History Manager Plugin.
    plugin: {
      "name": "History Manager Plugin"
    }
[1683319136883] INFO  (ext): registering Bookmarks Manager Plugin.
    plugin: {
      "name": "Bookmarks Manager Plugin"
    }
[1683319136883] INFO  (ext): registering Authentication Provider Plugin.
    plugin: {
      "name": "Authentication Provider Plugin",
      "isRegistered": false
    }
[1683319136884] INFO  (ext): SQLTools activation completed. 9.830333 ms
[1683319136884] INFO  (ext): Formatter Plugin registered!
[1683319136884] INFO  (ext): CodeLens Plugin registered!
[1683319136884] INFO  (ext): Dependency Manager Plugin registered!
[1683319136884] INFO  (ext): Connection Manager Plugin registered!
[1683319136884] INFO  (ext): History Manager Plugin registered!
[1683319136884] INFO  (ext): Bookmarks Manager Plugin registered!
[1683319136884] INFO  (ext): Authentication Provider Plugin registered!
[1683319137029] INFO  (ls): SQLTools Server started!
===============================
Using node runtime?: no
ExecPath: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) 
===============================
[1683319137033] INFO  (ext): LanguageClient ready
    ns: "lc"
[1683319137033] INFO  (ls): Initialized with node version:v16.17.1
[1683319137883] INFO  (ext): EXECUTING COMMAND => sqltools.refreshTree
[1683319137884] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1683319138888] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1683319178828] INFO  (ext): registering SQLTools Teradata Driver Plugin (driver).
    plugin: {
      "extensionId": "ScriptPup.sqltools-teradata-driver",
      "name": "SQLTools Teradata Driver Plugin",
      "type": "driver"
    }
[1683319178828] INFO  (ls): REQUEST RECEIVED => ls/RegisterPlugin
[1683319178829] INFO  (ls): request to register plugin: "/Users/username/.vscode/extensions/scriptpup.sqltools-teradata-driver-0.3.4/out/ls/plugin.js"
[1683319178897] ERROR (ls): Error registering plugin: {}
    error: {}
[1683319178898] ERROR (ext): ERROR: Error loading plugin SQLTools Teradata Driver Plugin Request ls/RegisterPlugin failed with message: No native build was found for platform=darwin arch=arm64 runtime=electron abi=110 uv=1 armv=8 libc=glibc node=16.17.1 electron=22.4.8
    loaded from: /Users/username/.vscode/extensions/scriptpup.sqltools-teradata-driver-0.3.4/node_modules/ref-napi
, {"code":-32603}
    ns: "error-handler"
[1683319179833] INFO  (ext): EXECUTING COMMAND => sqltools.refreshTree
[1683319179833] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1683319181878] INFO  (ext): EXECUTING COMMAND => sqltools.showOutputChannel
```

**Comment by Austin1** [comment] 2023-05-05 20:52
So I tried pulling the latest master branch and running it in VSCode as development extension and get a different error:
<img width="462" alt="image" src="https://user-images.githubusercontent.com/341408/236566616-6d055066-0dbd-4a8c-9043-af4a12fc1569.png">

```
[1683319889982] INFO  (ls): Initialized with node version:v16.17.1
[1683319889985] INFO  (ls): REQUEST RECEIVED => ls/RegisterPlugin
[1683319889985] INFO  (ls): request to register plugin: "/Users/username/Documents/GitHub/sqltools-teradata-driver/out/ls/plugin.js"
[1683319890053] ERROR (ls): Error registering plugin: {}
    error: {}
[1683319890054] ERROR (ext): ERROR: Error loading plugin SQLTools Teradata Driver Plugin Request ls/RegisterPlugin failed with message: Error in native callback, {"code":-32603}
    ns: "error-handler"
[1683319890916] INFO  (ext): EXECUTING COMMAND => sqltools.refreshTree
[1683319890916] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1683319891876] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
```

**Comment by adamtwo** [comment] 2023-05-12 01:06
@ScriptPup , long time no talk :). 

I've another user on Windows who reported the same issue with the same error code, but on Windows:
```
[1683852174342] ERROR (ext): ERROR: Error loading plugin SQLTools Teradata Driver Plugin Request ls/RegisterPlugin failed with message: Error in native callback, {"code":-32603}
```

Are you able to tell which part of native code is it coming from? Does it look to you as if it was coming from the teradata nodejs driver?

**Comment by Austin1** [comment] 2023-05-12 14:40
I can't tell.. I just tried again, i'm not sure how to answer your questions since I dont know what exactly is happening.

Tried looking through a bunch of code but really its the blind leading the blind here as I'm not a developer.

```
[1683901981707] INFO  (ls): Initialized with node version:v16.17.1
[1683901981710] INFO  (ls): REQUEST RECEIVED => ls/RegisterPlugin
[1683901981710] INFO  (ls): request to register plugin: "/Users/m16575/Documents/GitHub/sqltools-teradata-driver/out/ls/plugin.js"
[1683901981843] ERROR (ls): Error registering plugin: {}
    error: {}
[1683901981844] ERROR (ext): ERROR: Error loading plugin SQLTools Teradata Driver Plugin Request ls/RegisterPlugin failed with message: Error in native callback, {"code":-32603}
    ns: "error-handler"
[1683901982686] INFO  (ext): EXECUTING COMMAND => sqltools.refreshTree
```

**Comment by gjsjohnmurray** [comment] 2023-05-12 15:26
And perhaps https://github.com/microsoft/vscode/issues/181678 is relevant too, assuming you're using VS Code 1.78. If you are, can you try downgrading to 1.77?

**Comment by ScriptPup** [comment] 2023-05-15 12:41
Back at you @adamtwo! Is your user running windows 10 or windows 11? #25 appears to be very similar to this for windows 11.

@gjsjohnmurray's suggestion that this is due to the node version seems possible. I haven't been able to reproduce this on my system, but there may be some incompatibility with another installed package that I don't have or something of that nature.

I think getting more environment details may be helpful. The original errors @Austin1 posted are a bit strange since they mention a Debian build being missing when they're trying to install on a Mac. 

I've only had time for a pretty cursory check so far, but I'm not finding the statement `Error in native callback` directly in the tdnode driver, the teradata plugin, or the sqltools package. So either that's coming directly from a binary, or the error statement is more dynamic in nature.

I'm currently in the middle of renovations for moving house, so I'll have pretty spotty availability in the upcoming weeks (months?), but I'll hopefully have some more time to check further this evening. Any additional environment information that you all could provide would likely we helpful.

**Comment by adamtwo** [comment] 2023-05-15 18:36
> And perhaps [microsoft/vscode#181678](https://github.com/microsoft/vscode/issues/181678) is relevant too, assuming you're using VS Code 1.78. If you are, can you try downgrading to 1.77?

I'm on a Mac and the extension stopped working when I upgraded to 1.78. I think you are right. VS Code 1.78 upgraded [Electron to version 22](https://code.visualstudio.com/updates/v1_78#_electron-22-update). That brought in node.js 16.17.1. The extension relies on the Teradata node.js driver which in turn depends on `ffi-napi`. The library doesn't work with node.js 16.

The only workaround that comes to my mind is to downgrade VS Code to 1.77: https://code.visualstudio.com/updates/v1_77.

**Comment by ScriptPup** [comment] 2023-05-17 23:31
Hi @adamtwo, any chance you were able to downgrade the VSCode version to test? I haven't been able to reproduce the error on my system, but I'm running windows 10. The two reports of this error are from Mac and Windows 11; and I don't have access to either.

**Comment by adamtwo** [comment] 2023-05-23 04:48
> Hi @adamtwo, any chance you were able to downgrade the VSCode version to test? I haven't been able to reproduce the error on my system, but I'm running windows 10. The two reports of this error are from Mac and Windows 11; and I don't have access to either.

I confirm that downgrading to 1.77 resolves the issue on my Intel Mac.

**Comment by djonthehouse** [comment] 2023-06-02 01:41
I have the same error on MacOS as Austin1. Was that ever solved? Thanks !

**Comment by ScriptPup** [comment] 2023-06-02 02:03
I believe as of now the workaround is to downgrade VSCode to 1.77 until https://github.com/microsoft/vscode/issues/181678 is resolved.

**Comment by adamtwo** [comment] 2023-06-02 05:04
Correct, to have the extension work again, you have to downgrade to VSCode 1.77. 

On a related note, this workaround works for intel macs. If you have an M1/M2 mac, this is still no supported by the Teradata node.js driver and won't work even on VSCode .177.

**Comment by Austin1** [comment] 2023-06-14 19:43
@adamtwo  thank you for this clarification. I'm on an M1 Mac and so that's probably why I'm getting all the issues. Does this issue resolve the M1/M2 issue? https://github.com/worksofliam/blog/issues/51

**Comment by Austin1** [comment] 2023-10-02 20:15
I back over here being annoyed by this issue -- do we know if this extension uses node-odbc? I was following breadcrumbs from above and wondering if this is used in this extension and if it can be updated to maybe support ARM processors?

https://github.com/worksofliam/blog/issues/51#issuecomment-1294096824

**Comment by adamtwo** [comment] 2023-10-02 23:09
> I back over here being annoyed by this issue -- do we know if this extension uses node-odbc? I was following breadcrumbs from above and wondering if this is used in this extension and if it can be updated to maybe support ARM processors?
> 
> [worksofliam/blog#51 (comment)](https://github.com/worksofliam/blog/issues/51#issuecomment-1294096824)

Hi @Austin1 , it's not related to `node-odbc`. Without going into too many details, many Teradata drivers, including the nodejs driver, depend on a library written in go that implements the Teradata wire protocol. This nodejs driver also depends on that go library. That library has not been compiled for ARM.

@ScriptPup, I'll reach out to you to discuss this.

**Comment by Austin1** [comment] 2023-10-13 16:50
I found this: https://support.teradata.com/knowledge?id=kb_article_view&sys_kb_id=50776fb787b5d9901aec53d73cbb357b

references GOSQL-87 having ARM support? Does that mean anything in this context?

**Comment by adamtwo** [comment] 2023-10-13 19:30
> I found this: https://support.teradata.com/knowledge?id=kb_article_view&sys_kb_id=50776fb787b5d9901aec53d73cbb357b
> 
> references GOSQL-87 having ARM support? Does that mean anything in this context?

@Austin1, yes, you are correct, Teradata drivers now support ARM. I have a PR https://github.com/ScriptPup/sqltools-teradata-driver/pull/26 to upgrade this extension to use a version of the driver that supports ARM. Please note, that this doesn't resolve the incompatibility with Node 16 so keeping VSCode downgraded to 1.77 will still be necessary even with the new driver.

**Comment by Austin1** [comment] 2023-11-07 01:17
Awesome, I'll try this tomorrow and see how it works locally at work. Where can I monitor this incompatibility with Node 16? I saw on the main ffi-napi issues page that someone thanked this person for their fork, it seems to be pretty updated.. no idea if that means anything for this project but thought I'd mention it!

https://github.com/lwahonen/node-ffi-napi/pkgs/npm/ffi-napi

**Comment by Austin1** [comment] 2024-01-05 14:28
well this is painful, I just downgraded to 1.76 and then tried your PR, but SQLTools requires 1.78.0, so I can't test without finding a way to build a downgraded version of SQLTools THEN building this verison.

**Comment by adamtwo** [comment] 2024-05-29 20:04
The extension now works on Macs when `sqltools.useNodeRuntime` property is to true. Basically, it tells SQL Tools to use an external nodejs instance to load the extension. As a result,  the extension doesn't use the same memory space as Electron and avoids native errors in memory management.
I've created a PR that adds info about the workaround to the README: https://github.com/ScriptPup/sqltools-teradata-driver/pull/29

**Comment by ScriptPup** [comment] 2024-06-13 00:13
Thanks to the updates @adamtwo contributed for 0.5.0, this should be resolved. I'm closing the issue out as it should be resolved. Let us know if you continue to have trouble!

**Closed by ScriptPup** 2024-06-13 00:13 UTC
Labels: bug
